name: create-whatever
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: geertvdc/setup-hub@master
      - run: git switch master
      - run: yarn install
      - run: yarn release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
